language: python

python:
  - 2.7

before_install:
    - pip install pytest peewee python-coveralls nose

script:
    - pip install .
    - nosetests --tests=tests --with-coverage --cover-package=active_peewee

after_success:
  - coveralls

notifications:
    email:
        recipients:
            - felipevolpone@gmail.com
        on_success: change
        on_failure: always
